package jokes

var Jokes = []string{
    "Why don't scientists trust atoms? Because they make up everything!",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "How does a penguin build its house? Igloos it together.",
    "Why did the bicycle fall over? It was two-tired.",
    "I told my computer I needed a break, and now it won't stop sending me Kit-Kats.",
    "Why did the math book look sad? It had too many problems.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Did you hear about the claustrophobic astronaut? He needed a little space.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I would avoid the sushi if I was you. It's a little fishy.",
    "Why can't you trust stairs? Because they're always up to something.",
    "I used to play piano by ear, but now I use my hands.",
    "Why do cows wear bells? Because their horns don't work.",
    "I got a job at a bakery because I kneaded dough.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "Did you hear about the Italian chef that died? He pasta way.",
    "What's orange and sounds like a parrot? A carrot.",
    "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
    "Did you hear about the kidnapping at the playground? They woke up.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What's brown and sticky? A stick.",
    "I used to hate facial hair, but then it grew on me.",
    "How do you organize a space party? You planet.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "I would tell you a chemistry joke, but all the good ones argon.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I'm terrified of elevators, so I'm going to start taking steps to avoid them.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Want to hear a construction joke? Oh, never mind, I'm still working on it.",
    "Why was the math book sad? It had too many problems.",
    "What's Forrest Gump's email password? 1forrest1.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Did you hear about the guy who invented Lifesavers? He made a mint.",
    "I'm on a seafood diet. I see food and I eat it.",
    "What did the buffalo say when his son left? Bison.",
    "How do you make holy water? You boil the hell out of it.",
    "Why are elevator jokes so classic? They're uplifting.",
    "I'm reading a book on teleportation. It's bound to take me places.",
    "What did the fish say when he swam into a wall? Dam.",
    "I don't trust people who do acupuncture. They're backstabbers.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why don't scientists trust atoms? They make up everything.",
    "I would tell you a time-traveling joke, but you didn't like it.",
    "What do you call fake spaghetti? An impasta.",
    "Did you hear about the cheese factory explosion? There was de-brie everywhere.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they'd be bagels.",
    "I don't trust stairs. They're always up to something.",
    "Why did the coffee file a police report? It got mugged.",
    "How does a penguin build its house? Igloos it together.",
    "Why do bananas wear sunscreen? So they don't peel.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What did one hat say to the other? You stay here, I'll go on ahead.",
    "Why was the broom late? It swept in.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "Why did the mushroom go to the party? Because he's a fungi.",
    "Why did the fish blush? Because it saw the ocean's bottom.",
    "Why can't a nose be 12 inches long? Because then it would be a foot.",
    "Why did the bicycle stand up by itself? Because it was two-tired.",
    "What do you call a group of musical whales? An orca-stra.",
    "Why did the photo go to jail? It was framed.",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why was Cinderella so bad at soccer? She kept running away from the ball.",
    "How do cows stay up to date with current events? They read the moos-paper.",
    "Why was the computer cold? It left its Windows open.",
    "Why are frogs so happy? Because they eat whatever bugs them.",
    "What's a skeleton's least favorite room in the house? The living room.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "What do you call an alligator in a vest? An investigator.",
    "Why was the belt sent to jail? For holding up pants.",
    "Why did the dog sit in the shade? Because he didn't want to be a hot dog.",
    "How do trees access the internet? They log in.",
    "What do you call a factory that makes just OK products? A satisfactory.",
    "What did the duck say when it bought lipstick? Put it on my bill.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why do fish never do well in school? Because they're always below sea level.",
    "How does the moon cut his hair? Eclipse it.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I would make a joke about the sea, but it would be too deep.",
    "What does a cloud wear under his raincoat? Thunderwear.",
    "What did one plate say to the other? Lunch is on me.",
    "Why did the cookie go to the hospital? Because it felt crumby.",
    "What kind of exercise do lazy people do? Diddly-squats.",
    "Why was the math book sad? Because it had too many problems.",
    "What's brown and sticky? A stick.",
    "How do you organize a space party? You planet.",
    "Why did the cat sit on the computer? To keep an eye on the mouse.",
    "Why did the musician break up with his metronome? It wasn't keeping time.",
    "Why can't skeletons play music in church? They have no organs.",
    "Why don't secret agents get good grades? They're always undercover.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "What did the traffic light say to the car? Don't look, I'm changing!",
    "How do mountains stay fit? They hike.",
    "What kind of music do mummies listen to? Wrap.",
    "Why don't vampires use alarms? They're afraid of daylight savings.",
}
